### ISSUE TITLE
Error in playbook example?

### ISSUE THREAD

**Issue by hvdkooij** [CheckPointSW/CheckPointAnsibleGAIACollection#5]
I think there is an error in the playbook example:

```
---
- name: playbook name
  hosts: check_point
  connection: httpapi
  tasks:
    - name: task to have network
      check_point.mgmt.cp_gaia_hostname:
        name: "newhost"
```

I think it shoud be:

```
---
- name: playbook name
  hosts: check_point
  connection: httpapi
  tasks:
    - name: task to have network
      check_point.gaia.cp_gaia_hostname:
        name: "newhost"
```
