### ISSUE TITLE
check_point.gaia.cp_gaia_vlan_interface_facts throws error 500

### ISSUE THREAD

**Issue by chuegel** [CheckPointSW/CheckPointAnsibleGAIACollection#60]
We are using this collection to add VLAN interfaces to Checkpoint cluster nodes. While adding interfaces works as expected, the subsequent task:

```yaml
- name: Register VLAN interfaces of all members
  check_point.gaia.cp_gaia_vlan_interface_facts:
  register: gaia_int_vlan
```
fails with following error:

```bash
fatal: [fwinternet1]: FAILED! => changed=false 
  msg: 'Checkpoint device returned error 500 with message {''code'': ''generic_error'', ''errors'': ''1'', ''msg'': ''General Exception''}'
``` 

I must note that the two nodes have about 100 VLAN interfaces.

Versions used:
```
check_point.gaia              5.0.1

ansible [core 2.15.12]
python version = 3.9.19 (main, May 16 2024, 08:45:40) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)]
jinja version = 3.1.4
libyaml = True

OS: Gaia R81.20
HW: QLS250
```
